### ISSUE TITLE
README.md links not working

### ISSUE THREAD

**Issue by devang-kredx** [markerikson/redux-ecosystem-links#21]
Example, clicking on Forms opens https://github.com/markerikson/forms.md

**Comment by markerikson** [comment]
This seems to be some sort of a Github bug.  See https://twitter.com/dan_abramov/status/775332942268755969 and http://stackoverflow.com/questions/39445387/relative-link-in-readme-broken-if-readme-viewed-automatically-by-repo .  Not much I can do about it at the moment.

**Comment by markerikson** [comment]
Yep, see https://github.com/github/markup/issues/926 for details.
