### ISSUE TITLE
Do you mind evaluate and possibly add my immutable helper library ImmutableAssign to your Immutable Data section?

### ISSUE THREAD

**Issue by engineforce** [markerikson/redux-ecosystem-links#28]
Hi Mark,
I love your redux-ecosystem-links, it is really useful. Do you mind evaluate and possibly add my immutable helper library [ImmutableAssign](https://github.com/engineforce/ImmutableAssign) to your Immutable Data section?

Following is the advantages that differentiate it from other immutable libraries:

- It leaves your JS objects completely untouched (except the optional [deep-freeze](https://github.com/substack/deep-freeze)), it does not wrap around nor add any methods/properties to your JS objects.
- No magic keywords, such as $set, $push introduced by [Immutability Helpers](https://facebook.github.io/react/docs/update.html)
- It works really well with TypeScript, because of its [generic type argument inference](https://www.typescriptlang.org/docs/handbook/generics.html); and since you are working with plain JS objects (not the wrapper objects), you can utilize the full power of TypeScript: IntelliSense, type checking, and refactoring, etc.
- Works well with other libraries, such as lodash and underscore, please refer to the example 4 on its homepage.
- Extremely simple API (only one method), however since it works with other libraries such as lodash, it provides all the functionalities you need plus immutability.

Thanks

**Comment by markerikson** [comment]
Hey.  Saw your comment on Medium, and actually just added it. See 9d578bf9551505d592c085bc1675b575320c37a4 .

Looks useful.  The fact that it's actually doing a parse of the getter function is... interesting.  Kinda curious how well that works.  How does it handle object lookups that don't exist, ie`, a.b.c` where `b` isn't there?

**Comment by engineforce** [comment]
It will throw an exception: Cannot read property 'c' of undefined. I think this is expected behavior.

**Comment by engineforce** [comment]
In addition, this library has been fully unit tested in node.js and major browsers, and I have been using it in a production application works quite well.
