### ISSUE TITLE
could we startup a “editor's choices” project ?

### ISSUE THREAD

**Issue by zincli** [markerikson/redux-ecosystem-links#36]
Boom! My brain exploded while I'm scrolling the page, there are so many libraries.

I'm thinking of if some of redux experts could make a "editor's choices" of all these libraries?

It would be a huge shocked if this project is already a "editor's choices".

**Comment by markerikson** [comment]
Yeah, something of a "best-of" list would probably be useful.  Thus far I've simply cataloged anything that looks like it has some potential value and some reasonable amount of effort put into it.  

One of the tradeoffs of doing this list as just Markdown text is that there's no sorting or anything possible.  There's a much smaller but somewhat similar list at http://devarchy.com/redux , which I believe extracts information from the list at https://github.com/brillout/awesome-redux .  The Devarchy site is able to actually show information like number of Github stars and such.  

I do like the idea of some kind of "best-of" category or highlighting or something, but right now most of my time is taken up trying to write React+Redux posts for my blog.  I'm keeping up with adding links to this list and my React/Redux articles list on a weekly basis, but don't have serious time to devote to completely reworking things right now.

Both of my links list have been solo projects so far, but if someone wanted to help contribute by working on organization or something, I'd be interested.

**Comment by zincli** [comment]
Thanks. That helps a lot.
