### ISSUE TITLE
About reduxlet

### ISSUE THREAD

**Issue by Rokt33r** [markerikson/redux-ecosystem-links#45]
One of my acquaintance introduces here to me. Would it be possible my library to be listed?
https://github.com/Rokt33r/reduxlet

It is a hoc which provides a isolated redux store(and redux-saga) to a react component.

Thank you. 😁

**Comment by markerikson** [comment]
Already in the list :)  See the [Variations](https://github.com/markerikson/redux-ecosystem-links/blob/dfa9c2f67cb6b57e687559f6f02c0d8be703cb0f/variations.md) page.
