### ISSUE TITLE
Add lib to `react-ecosystem-links`

### ISSUE THREAD

**Issue by jpstone** [markerikson/redux-ecosystem-links#62]
I recently published a library that abstracts away Ramda lenses and uses them to create namespaced paths--each one being a closure that you can add an action/reducer pair to, and the action type gets prefixed with the path via dot notation. I created the lib after not quite finding what I needed in existing libs. 

Mind taking a look over and see if it's worth adding to this list?

https://www.npmjs.com/package/redux-pathspace

Thanks!

**Comment by markerikson** [comment]
Hah, beat you to it :)  I don't have the latest set of updates pushed up yet, but I already added it to my local version of the list.  Will probably push those changes up tomorrow.
