### ISSUE TITLE
Add Rematch to list of utilities

### ISSUE THREAD

**Issue by ShMcK** [markerikson/redux-ecosystem-links#66]
Add [Rematch](https://github.com/rematch/rematch) to list of utilities. It could possibly fit under a new category of "Frameworks".

Rematch is a framework that provides a simplified API for using Redux.

**Comment by markerikson** [comment]
I already have it listed in the ["Variations"](https://github.com/markerikson/redux-ecosystem-links/blob/4703b3c52d15b62499fe271adf9856ac482ccffe/variations.md) page.

And yes, that page is in desperate need of some organization into subcategories.  I don't have time to do it myself, but I'd definitely welcome a PR that helped clean up and organize that page.
